### ISSUE TITLE
Problem with redirect from URL with trailing / 

### ISSUE THREAD

**Issue by alexsb** [jekyll/jekyll-redirect-from#101]
I'm redirecting from URLs with a trailing slash, here is one example: 
[http://caleydo.org/projects/stratomex/](http://caleydo.org/projects/stratomex/)

I use this redirect_from:
```redirect_from: /projects/stratomex.html``` as instructed in #84 to overcome the MIME type issue. 

Now, this works beautifully locally, for both the version with the trailing slash and without it, but  when I host this on github pages, only the version without the trailing slash works: 

[http://caleydo.org/projects/stratomex](http://caleydo.org/projects/stratomex)

I suspect that's not strictly an issue with jekyll-redirect-from, but I'd appreciate any advice on workarounds.

**Comment by parkr** [comment]
@alexsb Are you still experiencing this?

**Comment by alexsb** [comment]
No, this works beautifully now! Thanks, much appreciated.
