### ISSUE TITLE
github-pages generates https

### ISSUE THREAD

**Issue by serialseb** [jekyll/jekyll-redirect-from#102]
I have a _config.yml with url: http://serialseb.com

Locally I have * jekyll-redirect-from (0.9.1) and * github-pages (52)
This is a github pages apex domain with a cname to their servers.

In /about/cv/ I have a `redirect_from: /cv/` 

Locally, this generates a redirect correctly using `/about/cv/`. On github, it's doing a full uri with `https://serialseb.com/about/cv/`, which of course doesnt work as there isnt https support for github pages.

I've opened a ticket with them but thought i'd see here too if the problem could be on this side.

**Comment by akoeplinger** [comment]
This should be fixed as of yesterday (you need to rebuild your site): https://twitter.com/benbalter/status/705114935777501185

**Comment by parkr** [comment]
Yep, just a bug on GitHub Pages.
