### ISSUE TITLE
Redirect page inherits default template if set via frontmatter defaults for posts

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-redirect-from#105]
### Steps to reproduce

1. Create a post
2. Set a deafult post layout via frontmatter defaults
3. Add redirect from front matter to the post

### Expected

Post is rendered as a redirect using the redirect template

### Actual

Post is rendered with the default front-matter template

### Example

`view-source:http://ben.balter.com/2015/04/27/eight-lessons-learned-hacking-on-github-pages-for-six-months/`

**Comment by pathawks** [comment]
Do we just need to add `:layout => nil` [here?](https://github.com/jekyll/jekyll-redirect-from/blob/v0.10.0/lib/jekyll-redirect-from/redirect_page.rb#L18)
