### ISSUE TITLE
Question: New Jekyll-redirect releases and GitHub Pages

### ISSUE THREAD

**Issue by caioproiete** [jekyll/jekyll-redirect-from#110]
Hello,

Could anyone point me to where I can find any information on when does GitHub gets new releases of Jekyll-redirect?

i.e. Once there's a new release tagged, how long does it usually take for GitHub to start using the new version?

Cheers.

**Comment by benbalter** [comment]
> i.e. Once there's a new release tagged, how long does it usually take for GitHub to start using the new version?

It depends on the complexity of the plugin and how much has changed since the last version (we review each change). Most of the time, the person releasing the plugin is the person performing the bump, so it can often be a matter of hours.

Is there something particular you had in mind? GitHub Pages is [currently running the latest version](https://pages.github.com/versions/).

**Comment by caioproiete** [comment]
Thanks @benbalter, that's very helpful.

I'm particularly interested in commit [f0ab71e](https://github.com/jekyll/jekyll-redirect-from/commit/f0ab71e1d8bf4d915fab59108b16fd665f5430ec) which is affecting me in a big website with lots of posts and, but also interested in a couple of issues that are currently open and looks like will be resolved soon, so just trying to have an estimate on when I could get those features / bug fixes.

More profoundly, I'm pondering what to do with a handful of websites I'm planning to host on GitHub: Use full GitHub Pages and let GH build it, or setup a separate build process (e.g. AppVeyor) for that.

I like the simplicity of using full GH-Pages, and not having the additional setup, but concerned if that would push me into a corner.

**Comment by danfowler** [comment]
@caioproiete Oh, it looks like we just got a version bump which will hopefully resolve the `redirect_to` issue on GitHub Pages once updated: https://github.com/jekyll/jekyll-redirect-from/releases/tag/v0.11.0

**Comment by parkr** [comment]
@danfowler Subscribe to https://github.com/github/pages-gem/pull/304 for a notification of when this ships to Pages.
