### ISSUE TITLE
Layout incorrectly applied to generated redirect pages

### ISSUE THREAD

**Issue by alexbaldwin** [jekyll/jekyll-redirect-from#112]
When running [html-proofer](https://github.com/gjtorikian/html-proofer#using-with-jekyll) on the redirect pages, I'm getting `Misplaced DOCTYPE declaration` warnings.

The offending line is producing `<!DOCTYPE html>`, but I'd prefer to set `layout: false` on these if it's generating it's own page without the need for a layout or be able to specify my own layout.

**Comment by pathawks** [comment]
Can you provide a bit more information? What exactly are you running html-proofer on? Can you upload an example offending page as a Gist?

Layouts should not be applied to redirect pages; [this should already be the case](https://github.com/jekyll/jekyll-redirect-from/blob/dd96265115988bcd607af858b7b06985f2510bb6/lib/jekyll-redirect-from/redirect_page.rb#L18)

**Comment by alexbaldwin** [comment]
@pathawks [here's an example](https://gist.github.com/alexbaldwin/fb031b5817ef75f843bde8ffbc8c911e#file-index-html-L70) and the `Gemfile.lock` for this build. Thank you Pat!

**Comment by pathawks** [comment]
Is your site source public?
In your config, are you specifying a default layout for pages? It looks like the [default layout is being applied to the redirect page](https://gist.github.com/alexbaldwin/fb031b5817ef75f843bde8ffbc8c911e#file-index-html-L70-L77) somehow.

**Comment by jdalton** [comment]
I'm seeing this issue too. Related to #94.

**Comment by pathawks** [comment]
Not related to 94.

Can you provide the source of a site that exhibits this behavior?

**Comment by jdalton** [comment]
If I modify a page [here](https://github.com/lodash/lodash.github.io) to use this plugin I see the same issue that @alexbaldwin outlined.

**Comment by parkr** [comment]
@jdalton I believe #106 fixed this issue. It has not been released yet. @pathawks, would you mind releasing a new version?

**Comment by jdalton** [comment]
:shipit: :)

**Comment by pathawks** [comment]
@parkr Do I have the privleges to cut a gem?

**Comment by parkr** [comment]
@pathawks You should! If you don't, let's get you access.

**Comment by pathawks** [comment]
I do not.

```text
$ script/release
jekyll-redirect-from 0.11.0 built to pkg/jekyll-redirect-from-0.11.0.gem.
Tagged v0.11.0.
Pushed git commits and tags.
rake aborted!
Pushing gem to https://rubygems.org...
You do not have permission to push to this gem.
```

**Comment by pathawks** [comment]
Good news! A new version has just been published to [RubyGems.org](https://rubygems.org/gems/jekyll-redirect-from/versions/0.11.0)! That should fix the issue. If not, please reopen this issue.

**Comment by alexbaldwin** [comment]
@pathawks @parkr thanks for your help! Upgraded to the new version and it works like a charm.
