### ISSUE TITLE
Styling the redirect page

### ISSUE THREAD

**Issue by davebowker** [jekyll/jekyll-redirect-from#128]
Hey,

Is there a way to style the redirect page? I know there is a small flash with a 0 second delay for those who have js enabled, but for those who do not could I specify a layout to use?

Thanks,
Dave

**Comment by evanberkowitz** [comment]
This would be great.  If instead of hard-coding the redirect page into `lib/jekyll-redirect-from/redirect_page.rb` the user could specify a `_layout` to use it'd allow much more easy and flexible customization.

**Comment by nikhiltri** [comment]
+1
