### ISSUE TITLE
Consider renaming

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll-redirect-from#134]
I wonder if the name of the repo could use a different name. Why **from**?

Maybe **jekyll-redirects**? **jekyll-redirector**?

**Comment by benbalter** [comment]
>  Why from?

Because IIRC, it started out as from (and has since expanded).

Don't disagree, but what would the user experience be like for gem users? (I'm fine changing the repo without changing the gem name)

**Comment by pathawks** [comment]
Yeah, changing the gem name is probably a bad idea. It probably makes sense to keep the repo and gem names the same.
