### ISSUE TITLE
private method `include' called for Jekyll::Page:Class

### ISSUE THREAD

**Issue by michaelcurry** [jekyll/jekyll-redirect-from#135]
Error building jekyll as of the new commits added 2 hours ago
```
/Library/Ruby/Gems/2.0.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'jekyll-redirect-from'. (Bundler::GemRequireError)
Gem Load Error is: private method `include' called for Jekyll::Page:Class
```

**Comment by benbalter** [comment]
Did some digging. This is because in Ruby < 2.2.0 `include` is a private method. Will get a PR going to move this to `:send` which should supporter Ruby >= 2.0.0 which is Jekyll's supported range.

**Comment by kristenzirkler** [comment]
I think I am also getting this error even after updating ruby to v2.6.8. 
Configuration file: /Users/kristenzirkler/Sites/hire-up-video/_config.yml
jekyll 3.3.1 | Error:  private method `include' called for Jekyll::Page:Class

**Comment by benbalter** [comment]
@kristenzirkler the fix (now in v0.12.1.) should also solve for that case as well. Can can you try upgrading and let us know if that's not true?

**Comment by kristenzirkler** [comment]
Perfect!!!! Thank You!

**Comment by michaelcurry** [comment]
@benbalter this fixed worked.  thank you for looking into this!
