### ISSUE TITLE
Redirecting to http://www.hireupvideo.com/http://www.hireupvideo.com/process/

### ISSUE THREAD

**Issue by kristenzirkler** [jekyll/jekyll-redirect-from#138]
Im sure this is somehow my setup but I just launched this site and now
http://www.hireupvideo.com/our_story is redirecting to:
http://www.hireupvideo.com/http://www.hireupvideo.com/process/

code in yaml header: 

redirect_from:
 - /our_story

repo:
https://github.com/kristenzirkler/hire-up-video

**Comment by benbalter** [comment]
Your problem is on this line of your configuration: https://github.com/kristenzirkler/hire-up-video/blob/gh-pages/_config.yml#L4

See http://ben.balter.com/jekyll-style-guide/config/#baseurl for an explanation.

**Comment by kristenzirkler** [comment]
PERFECT! Thank you! Sorry to bug.
