### ISSUE TITLE
Set Language

### ISSUE THREAD

**Issue by rogervila** [jekyll/jekyll-redirect-from#148]
Hello,

How can I translate the redirection page?
Can I do it from the `_config.yml` file?

If its not possible, I'd like to work on a PR.

Thank you.

**Comment by benbalter** [comment]
@rogervila You can customize the template, see https://github.com/jekyll/jekyll-redirect-from#customizing-the-redirect-template.

**Comment by rogervila** [comment]
Sorry, I didn't see that. Thank you very much.
