### ISSUE TITLE
Alternative ports are ignored

### ISSUE THREAD

**Issue by eksperimental** [jekyll/jekyll-redirect-from#154]
When setting an alternative port such as `4001`,
the direction will happen to port `4000`

**Comment by benbalter** [comment]
This is going to need to be fixed upstream in `jekyll/jekyll`. This plugin relies on `site.url`, which Jekyll sets. I suspect it may be hard coded to `4000` and not the user-specified port.

**Comment by eksperimental** [comment]
yes. if it set site.url with a port, it works, but I think it shouldn't be necessary

I will report it to jekyll then
thank you!

**Comment by eksperimental** [comment]
I updated to the latest version of jekyll and this plugin and the issue seems to be gone.
thank you @benbalter
