### ISSUE TITLE
Detect redirect from/to collisions and warn user at build time

### ISSUE THREAD

**Issue by ZiroKyl** [jekyll/jekyll-redirect-from#164]
- [x] I believe this to be a bug, not a question about using `jekyll-redirect-from`.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the **latest `github-pages`**

---

- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux

## My Reproduction Steps

1. The _author_ wrote two posts:

File: `_posts/2017-09-01-a-part1.html`
```
---
title: 'A Part1'
author: Copy-Paste Man
redirect_from: 
  - /abc/1/
---
```

**AND**

File: `_posts/2017-09-20-a-part2.html`
```
---
title: 'A Part2'
author: Copy-Paste Man
redirect_from: 
  - /abc/1/
---
```

2. Every time the _author_ run: `bundle exec jekyll serve`

## Expected Behavior

Get **error** or **warning**. Prefer **error**.

## Actual Behavior

`/abc/1/` redirect to `2017-09-20-a-part2`.

---

P.S. unfortunately, `permalink` have the same problem:
```
/p1.html          --{permalink to}--> /abc/1/
/p2.html          --{permalink to}--> /abc/1/
/abc/1/index.html
```

Result: `/_site/abc/1/index.html` is `/p2.html`

**Comment by ZiroKyl** [comment]
I taped :vhs: some workaround to this problem.

~~Stuped~~ Slow Workaround
--------------------------

Create file `/checker.html`:
```
---
empty_array: []
---
{%- assign pathnames = page.empty_array -%}


{%- for post in site.posts -%}
	{%- for pathname in post.redirect_from -%}
		{%- if pathnames contains pathname -%}
			Collision detected! Comment this line to print all collisions. {{ 0 | divided_by:0 }}
			`redirect_from` pathname "{{ pathname }}" in post "{{ post.path }}"
		{%- else -%}
			{%- assign pathnames = pathnames | push: pathname -%}
		{%- endif -%}
	{%- endfor -%}
{%- endfor -%}
{%- comment %} Additionally check site.pages, site.documents and site.static_files {% endcomment -%}
```

If `checker.html` detect collision you get **error** message:
```
Liquid Exception: Liquid error (line 7): divided by 0 in /checker.html
Error: Run jekyll build --trace for more information.
```

### Pefomance testing

And I did some performance tests of **array.add(string)** implementations.

```
---
empty_array: []
new_line: "\n"
---
{% assign arr = page.empty_array %}
===================================

{% for i in (0..10000) %}
	{% assign str_arr = "123" | split: page.new_line %}
	{% assign arr     = str_arr | concat: arr %}
{% endfor %}

 VS

{% for i in (0..10000) %}
	{% assign str_arr = "123" | split: page.new_line %}
	{% assign arr     = arr | concat: str_arr %}
{% endfor %}

===================================

Fastest(x4): `str_arr | concat: arr`

===================================

{% for i in (0..10000) %}
	{% assign arr = "123" | split: page.new_line | concat: arr %}
{% endfor %}

 VS

{% for i in (0..10000) %}
	{% assign arr = arr | push: "123" %}
{% endfor %}

 VS

{% for i in (0..10000) %}
	{% assign arr = arr | unshift: "123" %}
{% endfor %}

===================================

Parity.
```

**Comment by pathawks** [comment]
In general, I don't think that Jekyll does any checking at all to make sure each URL is unique. I don't think this plugin should be a special case.

I certainly agree that something like this would be useful when debugging, and I can remember a couple error reports that would have benefitted from this check, but I think that any duplicate URL checks should be done by Jekyll itself rather than by individual plugins.

**Comment by pathawks** [comment]
https://github.com/jekyll/jekyll/issues/6207

**Comment by benbalter** [comment]
I'm in agreement with @pathawks and think this is better solved upstream in https://github.com/jekyll/jekyll/issues/6207 as conflicts are not specific to this plugin.
