### ISSUE TITLE
Calling 'site.docs_to_write' prevents other generators from working properly

### ISSUE THREAD

**Issue by RadoslavK** [jekyll/jekyll-redirect-from#199]
Calling `site.docs_to_write` in `generator.rb` will make the site object remember the result of the first call which means that content generated later from other generators will not be taken into consideration. Took me a lot of time to figure out why is my content not being generated anymore.

**Comment by ashmaroli** [comment]
@RadoslavK What version of Jekyll are you using..?

**Comment by RadoslavK** [comment]
@ashmaroli 3.8.5, I have fixed the issue with a higher plugin priority

**Comment by ashmaroli** [comment]
This is probably because of the caching incorporated into the method:
```ruby
    # Get the to be written documents
    #
    # Returns an Array of Documents which should be written
    def docs_to_write
      @docs_to_write ||= documents.select(&:write?)
    end
```

**Comment by RadoslavK** [comment]
I am not sure why Jekyll allows calling that method from the outside. Maybe you could rethink the usage of `documents.select(&:write?)` directly, so any other generator's new documents are not omitted unless  _jekyll-redirect-from_ is called last. Jekyll internally calls `docs_to_write` when writing the final output.

**Comment by DirtyF** [comment]
This should be fixed in Jekyll core.
