### ISSUE TITLE
Anchor support

### ISSUE THREAD

**Issue by adumont** [jekyll/jekyll-redirect-from#219]
More a question than an issue per se.

My index.md reads like this:

```
---
[...]
redirect_from:
  - /projects/
---
```
Redirect work great.

Say I have an anchor `<a name="test"></a>` in index.md, I'd expect siteurl/projects#test to redirect to siteurl/#test, but instead I'm redirected to siteurl/. (anchor is lost). Is there any way to address that?

(my site is https://adumont.github.io/projects/ in case you want to see source see behaviour). 

https://adumont.github.io/#tplink-cloud-api opens fine (no redirect)
But https://adumont.github.io/projects#tplink-cloud-api redirects to https://adumont.github.io/, loosing the anchor :(

**Comment by Smutchings** [comment]
We're having a very similar issue on a clients website.

Loading /blog/tags#example from another page will lose the #example, loading only /blog/tags.
If I'm on /blog/tags already and I click a #example link within the page, it will then take me to the anchor within the page.

**Comment by satyanash** [comment]
Fragment identifiers like `#test` in your example are never sent in the HTTP request to the server[1]. Thus any response from the server (be it static or dynamic) cannot directly account for any fragments present in the URL.

However, you may be able to customize the `redirect.html`[2] to perform a client side javascript only redirect that reads the `window.location.hash` and appends it to the destination URL, before redirecting.

[1] https://tools.ietf.org/html/rfc7231#section-9.5
[2] https://github.com/jekyll/jekyll-redirect-from/blob/master/lib/jekyll-redirect-from/redirect.html

**Comment by satyanash** [comment]
Would vote to close this issue now.

**Comment by adumont** [comment]
Thanks a lot @satyanash for the aclaration.
