### ISSUE TITLE
How to set a relative URL?

### ISSUE THREAD

**Issue by bobvanluijt** [jekyll/jekyll-redirect-from#226]
How can I have the plugin set a relative URL in the generated pages? If I _not_ set `site.url` it defaults to `http://localhost:4000`

**Comment by ashmaroli** [comment]
`http://localhost:4000` is only set if you run `jekyll serve`.
Have you tried running `jekyll build` instead?

**Comment by bobvanluijt** [comment]
Aha – that's it. Sorry, did not know this
