### ISSUE TITLE
Redirect pages not working when deployed from Netlify

### ISSUE THREAD

**Issue by jglovier** [jekyll/jekyll-redirect-from#247]
The URLs just load a blank page rather than redirecting.

For example, based on the rules specified in the header for [jglovier.github.io/_posts/2011-06-29-html5-rant.md](https://github.com/jglovier/jglovier.github.io/blob/1cfe85d54aa967fe307e96f60b049bc71a31252b/_posts/2011-06-29-html5-rant.md?plain=1#L5-L7) I expect that the following URLs would redirect to https://joelglovier.com/writing/html5-rant
- https://joelglovier.com/writing/2011/html5-rant/
- https://joelglovier.com/html5-rant/

However, they do not.

I think I have everything configured correctly in the repository, but perhaps I'm missing something? I've had this setup for years and when I first installed it everything worked as expected. At that time I was hosting on GitHub Pages, so the only differences now are that I'm hosting on Netlify, and gem versions are now different for many gems (perhaps there is a recent conflict with later gem versions?).

**Comment by ashmaroli** [comment]
Your site has a custom `redirect` layout with [snippet:](https://github.com/jglovier/jglovier.github.io/blob/ccdb982395d8d26ac49435b952f3ba6bb5518457/_layouts/redirect.html#L4)
```
{% include head.html %}
```
which has:
```html
  {% if page.external_url %}
  <!-- for jekyll generated page redirects -->

  <meta http-equiv="refresh" content="0;url={{ page.external_url }}" />
  {% endif %}
```
So, a page gets redirection meta injected only if data key `external_url` is defined, which is not a feature from this plugin.

**Comment by jglovier** [comment]
OOooo wow - thanks for taking the time to spelunk and discover that, @ashmaroli!!! :bow: I don't recall the exact context there, but I think I had set it up years ago for including articles in my blog index that were on other sites. I can probably just remove that now.

Thank youuuu!

**Comment by ashmaroli** [comment]
> taking the time to spelunk..

Made me LOL on reading that.. :laughing: 
You're welcome! =)
