### ISSUE TITLE
All redirection urls are seen as pages by Jekyll

### ISSUE THREAD

**Issue by xplosionmind** [jekyll/jekyll-redirect-from#248]
If I loop through all pages of my website, by running:

```
{% for page in site.pages %}
  <li>{{ page.url }}</li>
{% endfor %}
```

…all of the URLs entered in the `redirect_from` field inside any page of the website are read as pages, not as URLs only.  
Hence, if I want to display/count/loop through all of the pages in my website, the result is that I cannot distinguish which one is an actual page, and which one is just a redirection URL.

<br />

#### Related

- <cite>[Loop through ALL pages of the website](https://talk.jekyllrb.com/t/loop-through-all-pages-of-the-website/6880)</cite> on Jekyll’s forum
- Example: see [this test page](https://tommi.space/test 'Test — tommi.space') ([source code](https://github.com/xplosionmind/tommi.space/tree/main/pages/test.html 'test.html — tommi.space'))

**Comment by ashmaroli** [comment]
@xplosionmind This is by design.
Since Jekyll is a static site generator, this is the most optimal route.

When you access one of the redirection URLs, series of meta markup in the page's `<head>` forces the browser to navigate to the desired URL.

To filter out *redirection pages* from the list, check for their paths:
```
{% for page in site.pages %}
  {% if page.path contains 'redirect.html' %}{% continue %}{% endif %} 
  <li>{{ page.url }}</li>
{% endfor %}
```

**Comment by xplosionmind** [comment]
Thank you very much!

**Comment by ashmaroli** [comment]
> To filter out _redirection pages_ from the list, check for their paths:
> 
> ```
> {% for page in site.pages %}
>   {% if page.path contains 'redirect.html' %}{% continue %}{% endif %} 
>   <li>{{ page.url }}</li>
> {% endfor %}
> ```

Regarding the above code, you may choose to optimize with the following if you have a huge number of *pages* in your site:
```
{% for page in site.pages %}
  {% unless page.path contains 'redirect.html' %}
  <li>{{ page.url }}</li>
  {% endunless %}
{% endfor %}
```
