### ISSUE TITLE
Browser downloads content of generated redirect file instead of redirecting

### ISSUE THREAD

**Issue by kortina** [jekyll/jekyll-redirect-from#37]
I have `redirect_from: /origins`in the frontmatter of the page generating http://kortina.net/essays/origins-of-venmo/ but when I go to http://kortina.net/origins, Chrome downloads a file with these contents instead of redirecting:

```
  <!DOCTYPE html>
  <meta charset=utf-8>
  <title>Redirecting...</title>
  <link rel=canonical href="/essays/origins-of-venmo">
  <meta http-equiv=refresh content="0; url=/essays/origins-of-venmo">
  <h1>Redirecting...</h1>
  <a href="/essays/origins-of-venmo">Click here if you are not redirected.</a>
  <script>location='/essays/origins-of-venmo'</script>
```

I am hosting on GitHub pages. It appears the page is being generated correctly--is it just not being served correctly perhaps?

**Comment by parkr** [comment]
Will Norris is working on a fix in Jekyll that will help this, I believe.

**Comment by 304NotModified** [comment]
This is closed, but not fixed?

See http://304notmodified.github.io/news

**Comment by Jonathan-Eyler-Werve** [comment]
Githup Pages is still suggesting the non-functional 
```
---
redirect_from: "/foo"
---
```
on their redirect-from docs. 

https://help.github.com/articles/redirects-on-github-pages/

**Comment by parkr** [comment]
> Github Pages is still suggesting the non-functional on their redirect-from docs

Please write an email to support@github.com about their docs. Include a link to the Help page and to your comment here. Thanks!
