### ISSUE TITLE
redirect from tries to acces front matter on static files

### ISSUE THREAD

**Issue by djacquel** [jekyll/jekyll-redirect-from#47]
Investigating on [this stackoverflow question](http://stackoverflow.com/questions/26280784/can-i-have-non-html-md-files-in-a-rendered-collection?noredirect=1#comment41250507_26280784) I've found that redirect from tries to acces front matter on static files.

Reproduce :
 - new jekyll site (2.4)
 - a collection with static files like .js or .css
 - jekyll-redirect
 - `jekyll build`

`Error : /var/lib/gems/1.9.1/gems/jekyll-redirect-from-0.6.2/lib/jekyll-redirect-from/redirector.rb:38:in `has_alt_urls?': undefined method `data' for #<Jekyll::StaticFile:0x00000001baa4e0> (NoMethodError)`

The Redirector:generate method at `generate_alt_urls(site, site.docs_to_write)` receive both collection files + static files, then method Redirector:has_alt_urls tries to access the unexisting method on statik file.

This is not reproduced in gh-page configuration as the `generate_alt_urls(site, site.docs_to_write)` doesn't exist.

**Comment by nashbridges** [comment]
Another example with [image and pdf files located withing collections directory](https://github.com/savchook/savchook.github.io/tree/master/_books/taranushenko-dereviana-monumentalna-arhitektura), which gives the same error if using jekyll-redirect-from
