### ISSUE TITLE
Redirects from a .html file aren't generated

### ISSUE THREAD

**Issue by SeanKilleen** [jekyll/jekyll-redirect-from#48]
Hi all,

I'm moving to Jekyll from Blogger (blargh) and this plugin seems to be exactly what I need -- thanks!

Blogger specifies exact html files for my posts, e.g. http://www.seankilleen.com/2012/06/how-to-remove-table-formatting-in-excel.html

The following works: `redirect_from: "/2012/06/how-to-remove-table-formatting-in-excel/"`

But my use case is: `redirect_from: "/2012/06/how-to-remove-table-formatting-in-excel.html"`

This does not seem to generate an HTML file with that exact name.

Am I missing something? I couldn't find anything in the docs about pages that require the actual `.html` extension.

If this isn't something that the plugin currently supports, let me know and I can attempt to dig in and contribute. Thanks!

**Comment by ndarville** [comment]
What exactly did you end up doing, @SeanKilleen?

**Comment by ndarville** [comment]
Figured it out from your commit log:

```diff
- redirect_from: foo.html
+ redirect_from:
+     - foo.html
```

**Comment by SeanKilleen** [comment]
@ndarville exactly right!

**Comment by parkr** [comment]
Thanks for jumping in, @ndarville!
