### ISSUE TITLE
Redirecting to github.com/<my user>  instead of my domain?

### ISSUE THREAD

**Issue by phstc** [jekyll/jekyll-redirect-from#66]
Hey

Probably I didn't understand this [prefix configuration](https://github.com/jekyll/jekyll-redirect-from#prefix) well. But I couldn't make the redirect to redirect to my domain, it's redirecting to github.com instead.

I would like to redirect http://www.pablocantero.com/blog/2015/03/14/sidekiq-(redis)-vs-shoryuken-(aws-sqs)/ to http://www.pablocantero.com/blog/2015/03/14/sidekiq-redis-vs-shoryuken-aws-sqs/ (the only one difference is the parenthesis)

So in order to do that I added the `redirect_from`:

```markdown
# _posts/2015-03-14-sidekiq-redis-vs-shoryuken-aws-sqs.md
layout: post
title: Sidekiq (Redis) vs Shoryuken (AWS SQS)
redirect_from:
  - /blog/2015/03/14/sidekiq-(redis)-vs-shoryuken-(aws-sqs)/
```

The redirect is def redirecting, but it's redirecting to https://github.com/phstc/blog/2015/03/14/sidekiq-redis-vs-shoryuken-aws-sqs (which does not exist) instead of  http://www.pablocantero.com/blog/2015/03/14/sidekiq-redis-vs-shoryuken-aws-sqs/.

In my `_config.yml` I have

```yaml
url: http://www.pablocantero.com/
baseurl: '/'
```

Any thoughts?

**Comment by phstc** [comment]
I've just found the "problem":

https://github.com/jekyll/jekyll-redirect-from/blob/6f537f1688c2e900bcc45a98716da932c0ffc70c/lib/jekyll-redirect-from/redirector.rb#L68

I have the `github.url` configured in my `_config.yml`, so it's using it instead of my `baseurl`.

Shouldn't this order here: 

```ruby
def redirect_prefix(site)
  config_github_url(site) || config_baseurl(site) || ""
end
```

Be the opposite:

```ruby
def redirect_prefix(site)
  config_baseurl(site) || config_github_url(site) || ""
end
```

???

**Comment by akoeplinger** [comment]
Don't name the key `github` in your `_config.yml`, that namespace is supposed to contain metadata for GitHub Pages: https://help.github.com/articles/repository-metadata-on-github-pages/

**Comment by phstc** [comment]
great! I didn't know that. but wouldn't that take precedence over `baseurl` as it's set by default?

**Comment by akoeplinger** [comment]
Yes, and that's what you usually want. Or why would you want something else?

**Comment by phstc** [comment]
For people using custom domains, they don't want to redirect to `github.url`, they want to redirect to `baseurl` or `url`.

> https://github.com/jekyll/jekyll-redirect-from#prefix
> Prefix
> 
> If site.baseurl is set, its value is used as a prefix for the redirect url automatically. This is useful for scenarios where a site isn't available from the domain root, so the redirects point to the correct path.
> 
> Note: If you are hosting your Jekyll site on GitHub Pages, the prefix is set to the pages domain name i.e. http://example.github.io/project or a custom CNAME.

With the current `redirect_prefix` I don't see a way to use GitHub Pages and redirect to a custom domain.

**Comment by akoeplinger** [comment]
`github.url` is set to your custom domain as configured in the `CNAME` file, so it is automatically used when redirecting (that was the whole point of it :smile: )

**Comment by phstc** [comment]
FML haha

The whole point of this "issue" was because I set `github.url`! 

Thanks a lot for helping me! 

Everything is working now.
