### ISSUE TITLE
Redirect other assets?

### ISSUE THREAD

**Issue by chimericdream** [jekyll/jekyll-redirect-from#68]
I am in the process of migrating a WordPress blog to GitHub Pages, and I plan to change the directory structure of my uploaded files. But I want to keep any external links redirecting to the new location. Since an image obviously doesn't have a front matter header, is this possible? If so, how do I set it up?

Thanks.

**Comment by parkr** [comment]
I don't think image redirects will work :( You'll be requesting an `image/jpeg`, for example, and getting back `text/html` with the redirect information...

**Comment by parkr** [comment]
But in general, this is a `redirect_to` page.

**Comment by chimericdream** [comment]
That's kind of what I was expecting, but thought I'd ask. Is there any plan to set up a way for redirects to be loaded from the `_config.yml` file? Not only would that enable the ability for redirects on non-HTML files, it would allow people to use regular expressions and handle numerous redirects without specifying each one in a separate file.
