### ISSUE TITLE
Requirements and how it works should be described.

### ISSUE THREAD

**Issue by iBobik** [jekyll/jekyll-redirect-from#73]
How redirects are performed?
Does it generate .htaccess for Apache? NginX conf?
It site is hosted on S3, does it generate XML with redirect rules?
Or it requires some server scripting? (So it will not works on static sites hostings?)

README should include answers.

**Comment by parkr** [comment]
This would be wonderful to add! Right now, all we have is `These pages will contain an HTTP-REFRESH meta tag which redirect to your URL.` randomly tucked in there.

Want to add a `How It Works` section? Redirects are performed by serving an HTML file with an HTTP-REFRESH meta tag which points to your destination. No `.htaccess` file, nginx conf, xml file, or anything else will be generated. It simply creates HTML files.

**Comment by iBobik** [comment]
The second paragraph you wrote it perfect explanation. I think you can put
it into README right now :-)



Jan Pobořil

2015-09-28 22:30 GMT-05:00 Parker Moore <notifications@github.com>:

**Comment by parkr** [comment]
Thanks!
