### ISSUE TITLE
Is index.html really needed in the redirected url?

### ISSUE THREAD

**Issue by ilg-ul** [jekyll/jekyll-redirect-from#74]
My site uses 'pretty' URLs, so no `index.html` appears in the address bar.

After adding a redirect, I noticed that the address bar shows `.../blog/index.html`, which is functional, but not consistent with the rest of the site.

Is there any way to get rid of the `index.html` in redirects?

**Comment by parkr** [comment]
What is the expected output? Can you try moving the file to you destination and ensuring it's served as HTML?

**Comment by ilg-ul** [comment]
the current output is:

```
<!DOCTYPE html>
<meta charset=utf-8>
<title>Redirecting...</title>
<link rel=canonical href="/blog/index.html">
<meta http-equiv=refresh content="0; url=/blog/index.html">
<h1>Redirecting...</h1>
<a href="/blog/index.html">Click here if you are not redirected.</a>
<script>location='/blog/index.html'</script>
```

I would expect something like

```
<!DOCTYPE html>
<meta charset=utf-8>
<title>Redirecting...</title>
<link rel=canonical href="/blog/">
<meta http-equiv=refresh content="0; url=/blog/">
<h1>Redirecting...</h1>
<a href="/blog/">Click here if you are not redirected.</a>
<script>location='/blog/'</script>
```

I did not try this, but any other idea that makes the redirected page not show the ending `/index.html` in the address bar should be fine.

**Comment by parkr** [comment]
Ok, now I see. What does your redirect_from statement look like?

**Comment by ilg-ul** [comment]
file `/blog/index.html`

```
---
layout: blog
title: GNU ARM Eclipse News
author: Liviu Ionescu
redirect_from:
  - /news/

---

{% if site.paginate %}
...
```

(full file available from https://github.com/gnuarmeclipse/gnuarmeclipse.github.io-source/blob/master/blog/index.html)

**Comment by brandonb927** [comment]
Came here to mention this as well. We use extension-less URLs on www.sendwithus.com and we're having an issue with the plugin where it's generating `.html` in the redirect path. 

Note: this is copied from minified HTML so there's no quotes in the URLs.

Expected output:
```
<!DOCTYPE html>
<meta charset=utf-8>
<title>Redirecting...</title>
<link rel=canonical href=/resources/components>
<meta http-equiv=refresh content="0; url=/resources/components">
<h1>Redirecting...</h1><a href=/resources/components>Click here if you are not redirected.</a>
<script>
location = "/resources/components"
</script>
```

Generated output:
```
<!DOCTYPE html>
<meta charset=utf-8>
<title>Redirecting...</title>
<link rel=canonical href=/resources/components.html>
<meta http-equiv=refresh content="0; url=/resources/components.html">
<h1>Redirecting...</h1><a href=/resources/components.html>Click here if you are not redirected.</a>
<script>
location = "/resources/components.html"
</script>
```

**Comment by HugoGiraudel** [comment]
Confirmed.

**Comment by parkr** [comment]
I don't have time to look into this for the next few weeks, so if someone has time to fiddle with the code and submit a patch, it'd be much appreciated.
