### ISSUE TITLE
Using variables or liquid in the redirect_from value

### ISSUE THREAD

**Issue by nasht00** [jekyll/jekyll-redirect-from#78]
Can I make the redirect_from value include variables such as {{page.url}} or more complex values?

I have hundreds of pages that changed url structure and need a way to quickly map all of them to the new url...

**Comment by parkr** [comment]
Not at the moment, but @gjtorikian made jekyll-conrefifier (sp?) which would enable this.

**Comment by gjtorikian** [comment]
Yup: https://github.com/gjtorikian/jekyll-conrefifier

**Comment by mpchadwick** [comment]
For anyone else viewing this, I published this last night which might also help in cases where there are a large amount of URLs that are changing https://github.com/mpchadwick/jekyll-migrate-permalink
