### ISSUE TITLE
Be able to control prefix even if on GitHub Pages

### ISSUE THREAD

**Issue by dentarg** [jekyll/jekyll-redirect-from#81]
If I read the source correctly, you always prefer `site.github.url` if it's set.

Would it make sense to introduce another variable to be used, even if `site.github.url` is set?

We use GitHub Pages, but we don't use the CNAME file, because we have our own proxy and cache before GitHub Pages.

**Comment by dentarg** [comment]
> We use GitHub Pages, but we don't use the CNAME file, because we have our own proxy and cache before GitHub Pages.

The use case for this is that we want to avoid SSL errors if someone tries HTTPS and our custom domain name.

**Comment by parkr** [comment]
I'm kinda torn on this. One thing to do in the meantime is to just write a layout that uses our redirect HTML and hook it in with some front matter variables and write the redirection pages yourself.

/cc @benbalter

**Comment by benbalter** [comment]
Is there any reason not to default to `site.url`, if set, and then fall back to `site.github.url`?

**Comment by parkr** [comment]
@benbalter That would be just fine.

**Comment by dentarg** [comment]
@parkr @benbalter like this?

```diff
$ git diff
diff --git a/lib/jekyll-redirect-from/redirector.rb b/lib/jekyll-redirect-from/redirector.rb
index 40db8c3..91b7067 100644
--- a/lib/jekyll-redirect-from/redirector.rb
+++ b/lib/jekyll-redirect-from/redirector.rb
@@ -69,7 +69,11 @@ module JekyllRedirectFrom
     end

     def redirect_prefix(site)
-      config_github_url(site) || config_baseurl(site) || ""
+      config_url(site) || config_github_url(site) || config_baseurl(site) || ""
+    end
+
+    def config_url(site)
+      site.config.fetch('url', nil)
     end

     def config_github_url(site)
```

and adjustment of specs

**Comment by benbalter** [comment]
:+1:

**Comment by dentarg** [comment]
Hmm... what's the reason for closing this?

**Comment by parkr** [comment]
@dentarg A mistake – sorry!
