### ISSUE TITLE
Implement setting for whether quotes are single or double

### ISSUE THREAD

**Issue by ndarville** [jekyll/jekyll-redirect-from#82]
By default, `htmlhint` flags HTML that uses single quotes in attribute values. While the default behaviour is fine, it would be nice with an option to change the quote output to double. :)

**Comment by parkr** [comment]
Maybe we should just switch to double quotes.

**Comment by ndarville** [comment]
I’d be down with that.

**Comment by parkr** [comment]
Want to submit a PR?
