### ISSUE TITLE
Jekyll 3 starting to download file instead of redirecting

### ISSUE THREAD

**Issue by luckyraul** [jekyll/jekyll-redirect-from#84]
```
permalink: /contacts/
redirect_from:
 - /contact-information
```
When I passed to /contact-information browser was not redirecting as expected, but **downloaded file** with correct html

```
<!DOCTYPE html>
<meta charset=utf-8>
<title>Redirecting...</title>
<link rel=canonical href="/contacts/">
<meta http-equiv=refresh content="0; url=/contacts/">
<h1>Redirecting...</h1>
<a href="/contacts/">Click here if you are not redirected.</a>
<script>location='/contacts/'</script>
```

**Comment by chriddyp** [comment]
:+1: I'm seeing the same thing, yikes!

**Comment by TimoSolo** [comment]
getting the same problem on ghpages

redirect_from: 
  - /3books/
  - /3books

without the / downloads, and with a / gives a 404 :(

**Comment by parkr** [comment]
This is because the default mime type is application/octet-stream. It has to be a .html file to be served properly, unfortunately.

**Comment by luckyraul** [comment]
The solution is in my case to rewrite /contact-information to - /contact-information.html so the result file will be properly served as /contact-information
