### ISSUE TITLE
When is the plugin running?

### ISSUE THREAD

**Issue by nasht00** [jekyll/jekyll-redirect-from#87]
I am trying to inject `redirect_from` properties during the build time, via a hook plugin.

When  I use the `pages` `pre-render` hook, the redirect-from plugin does not seem to pickup the property.

Using `post_init` does not let me edit the page's properties.

Any ideas?

**Comment by parkr** [comment]
This is run during the `generate` phase: https://github.com/jekyll/jekyll/blob/master/lib/jekyll/site.rb#L52-L63

The `pre_render` hook has both the page payload and the site payload – both may need to be updated.
