### ISSUE TITLE
Can I use a redirection using the url pattern?

### ISSUE THREAD

**Issue by metasmile** [jekyll/jekyll-redirect-from#90]
hello,
I'm making a landing page that supports the localization.
So, my expect result is :
```
http://domain.com/fr-FR
http://domain.com/fr_FR
http://domain.com/fr
http://domain.com/fr-US
```

And yes, they must redirect to same url.
My question is : Can I write as below (or use any patterns)?

```
redirect_from:
  - /fr*
```

Instead of 

```
redirect_from:
  - /fr-FR
  - /fr-CA
  - /fr-US
```

**Comment by parkr** [comment]
No, unfortunately this is not possible. Please see my comment here: https://github.com/jekyll/jekyll-redirect-from/issues/80#issuecomment-152628082

**Comment by metasmile** [comment]
hmm, ok. It looks clear intention. But I think that you might need it someday..
Thanks for your comment since nanoseconds. :)
