### ISSUE TITLE
Redirect to extensionless url

### ISSUE THREAD

**Issue by fulldecent** [jekyll/jekyll-redirect-from#92]
I would like to get

 > /page.html -- is the file created by Jekyll
 > /page -- is how I link to the file and GitHub Pages serves the page.html page
 > /page.php -- this page gets redirected to /page

I am attempting to get this with:

> Use `redirect_from: /page.php.html` on the page (GitHub will serve this when accessing /page.php)
> Use standard settings for permalink

The result I get is:

 > /page.html -- is created
 > /page -- is accessible
 > /page.php -- redirects to page.html

Please advise if it possible to get the desired behavior.

**Comment by parkr** [comment]
@fulldecent If you're using GitHub Pages to build your site, this is not presently possible as Jekyll 3 has not yet shipped there: github/pages-gem#175. Let me know if this is not the case.

**Comment by fulldecent** [comment]
Understood, thank you. Closing as this is just simply a dependency on github/pages-gem#175

**Comment by parkr** [comment]
Thanks, @fulldecent! We'll hopefully ship Jekyll 3 on GitHub Pages in the coming month or two.
