### ISSUE TITLE
Upgrade to Jekyll v3?

### ISSUE THREAD

**Issue by p4m** [jekyll/jekyll-redirect-from#97]
Any plans in upgrading to Jekyll v3?

**Comment by benbalter** [comment]
It currently works with and is [tested against Jekyll 2 and Jekyll 3](https://github.com/jekyll/jekyll-redirect-from/blob/master/.travis.yml#L25-L26). Are you seeing behavior indicating otherwise?

**Comment by p4m** [comment]
Hmmm. That sounds I have a local problem.

I get the following error when starting Jekyll with the plugin activated:
![image](https://cloud.githubusercontent.com/assets/1651685/12823416/2ef53eec-cb6c-11e5-88b4-732a199430d7.png)

How can I update this gem (v0.7) to the latest version?

**Comment by benbalter** [comment]
> How can I update this gem (v0.7) to the latest version?

`gem update jekyll-redirect-from` or `bundle update` if running bundler.

The current version is 0.9.1.

**Comment by p4m** [comment]
Thanks Ben, I appreciate your help!

Somehow the version of jekyll-redirect-from is linked to my current
Jekyll-site. After removing 0.7 completely from my system and installing
0.9.1, it complains that 0.7 cannot be found. A new Jekyll site
with jekyll-redirect-from gives no problem.
Is there an easy way to decouple v0.7 from an existing website? I have
appr. 45 websites running with 0.7?



Kind Regards,

Frank Welten

: publishfor.me

Wildenborchallee 43
6921 JZ  Duiven
The Netherlands

+31 6 54970030
www.linkedin.com/in/frankwelten

2016-02-04 18:39 GMT+01:00 Ben Balter <notifications@github.com>:

**Comment by p4m** [comment]
Sorry, never mind. Found the file (Gemfile.lock) with version number.


Kind Regards,

Frank Welten

: publishfor.me

Wildenborchallee 43
6921 JZ  Duiven
The Netherlands

+31 6 54970030
www.linkedin.com/in/frankwelten

2016-02-04 20:18 GMT+01:00 Frank Welten <frank@publishfor.me>:
