### ISSUE TITLE
Roll in functionality from 'pageless redirects'?

### ISSUE THREAD

**Issue by alias1** [jekyll/jekyll-redirect-from#98]
I recently came across [jekyll-pageless-redirects](https://github.com/nquinlan/jekyll-pageless-redirects) which seemed quite cool, but it looks pretty unmaintained. It would be cool to see the functionality rolled into this project, and then we'd have 'one jekyll redirect solution to rule them all' :)

If it's a thing you'd be open to including, I could look at potentially hacking together a PR for it. (though if someone has more time/familiarity that would like to do it, that would be cool)

**Comment by parkr** [comment]
@alias1 This plugin can't generate unsafe content such as the `.htaccess` file. Unfortunately, for now, we must stick with the redirect pages, even though it's not technically The Right Thing to do.

**Comment by alias1** [comment]
Ah, fair enough. That makes sense.

Sent from Outlook Mobile




On Mon, Feb 8, 2016 at 12:12 PM -0800, "Parker Moore" <notifications@github.com> wrote:












@alias1 This plugin can't generate unsafe content such as the .htaccess file. Unfortunately, for now, we must stick with the redirect pages, even though it's not technically The Right Thing to do.
